name: first job for github actions

on:
    push:
        branches: ['development']

jobs:
    build:
        runs-on: ubuntu-latest  
    
        steps:
            - name: testing job
              uses: actions/checkout@v4

            - name: install project requirements  
              run: pip install -r requirements.txt 

            - name: change dir
              run: |
                cd BackEnd
                echo "Successfully in Backend repository"
                pwd
                nohup python3 app.py  &
                sleep 5
                pkill -f app.py
                echo "Backend server running successfuly"

            # - name: run backend server
            #   run: |
            #     python3 /BackEnd/app.py  
            #     echo "Backend server runnigng successfuly"
              
            


              
