name: first job for github actions

on:
    push:
        branches: ['development']

jobs:
    build:
        runs-on: ubuntu-latest  
    
        steps:
            - name: testing job
              uses: actions/checkout@v4

            - name: install project requirements  
              run: pip install -r requirements.txt 

            - name: change dir
              run: |
                cd BackEnd
                pwd
                echo "Successfully in Backend repository"

            - name: run backend server
              run: |
                python3 /BackEnd/app.py  
                echo "Backend server runnigng successfuly"
              
            


              
