name: testing my first project 

on:
    push:
        branches: ['develpment']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout respository
              uses: actions/checkout@v4
              
            - name: print a simple statement  
              run: echo "building my first job with github actions" 
              
            - name: run anoter job test
              run: eco "Testing job again"
             
